### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by solkpolk** [pablopunk/nextjs-redirect#16]
Is it possible to redirect with a value from the original url?

Say the url looks like this:
website.com/redirect?key=value

and then the redirect becomes website.com/another-page?key=value

**Comment by pablopunk** [comment]
Sorry I missed this issue!

Right now it is not possible but I can make it happen ;)

**Comment by pablopunk** [comment]
@solkpolk done! It only works on server side for now, hope that's enough.

```bash
npm install nextjs-redirect@5.1.0
```

And [the docs are here](https://github.com/pablopunk/nextjs-redirect#redirect-to-url-from-parameters).

Cheers!
