### ISSUE TITLE
Option to add styles

### ISSUE THREAD

**Issue by jahirfiquitiva** [pablopunk/nextjs-redirect#5]
Hi

I know this might not be really necessary, but since redirection might take a second or so, I would like to apply some styles while it happens

Would you mind adding an option for that, please?

**Comment by pablopunk** [comment]
Hi! To better understand what you're asking for, can you provide some example code of how you would use styles with this package? Thanks :)

**Comment by jahirfiquitiva** [comment]
Basically, centering the text in the screen, or at least adding some padding, maybe even being able to show a custom component or text, maybe for i18n? those kinds of things 😅

**Comment by pablopunk** [comment]
`npm i nextjs-redirect@5`

I made it so you can use it as a HOC, [check out the docs](https://github.com/pablopunk/nextjs-redirect#custom-ui-component-hoc).

Thanks for the suggestion @jahirfiquitiva!
